let Add = (a, b) => a + b;
export { Add };
let Subtract = (a, b) => a - b;
export { Subtract };
let Multiply = (a, b) => a * b;
export { Multiply };
let Divide = (a, b) => a / b;
export { Divide };
let Power = (a, b) => a ** b;
export { Power };
